"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(_!+@@axbzjjiu&wr*o$)mn553oddn20hoyro9sa_dc(v%xh7q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'app.apps.AppConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cors
CORS_ALLOW_ALL_ORIGINS = True

# session 
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 有效期为两周
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# temp
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


'''
Database struct
'''
# Database path
# -
# database
# ----SRP123456
# --------anntation
# ------------SRP123456.faa
# --------pro_str
# ------------SRP123456_13456.pdb
# ------------SRP123457_13456.pdb
# ------------...
# --------final_contigs.fa
# --------resfinder.tab
# --------vfdb.tab
# --------SRP123456.gbk
# --------SRP123456.tsv
# --------gtdbtk.bac120.summary.tsv
# --------metawrap_50_10_bins.contigs
# --------metawrap_50_10_bins.stats
# --------macrel.out.prediction 
# --------SRP121432_combined.csv

#数据库根目录  
DATABASE_PATH = os.path.join(BASE_DIR, '/home/tecot/projects/dsm/database')



# bio工程表目录
SRP_INFO_FILE = 'bio_project_info.csv'

# 依据SRAStudy去重的bio工程表（手动生成的）
SRP_DEDUPLICATED_INFO_FILE = 'bio_project_deduplicated_info.csv'

# 每一个SRP项目对应的Contigs文件名
SRP_GENEOME_SEQ_FILE = 'final.contigs.fa'

# 每一个SRP项目对应的耐药基因文件名
SRP_RESFINDER_FILE = 'resfinder.tab'

# 每一个SRP项目对应的毒力基因文件名
SRP_VFDB_FILE = 'vfdb.tab'

# 每一个SRP项目对应的gtdbtk.summary文件名
GTDBTK_BAC120_SUMMARY_FILE = 'gtdbtk.summary.tsv'

# 每一个SRP项目对应的metawrap_50_10_bins.stats文件名
METAWRAP_50_10_BINS_FILE = 'metawrap_50_10_bins.stats'

# 每一个SRP项目对应的macrel.out.prediction文件名
MACREL_OUT_PREDICTION_FILE = 'macrel.out.prediction'

# 文件下载前缀名
DOWNLOAD_FILE_PRENAME = 'DeepSeaMicro'

# 外部VFDB文件数据路径
EXTERNAL_VFDB_PATH = os.path.join(BASE_DIR, 'datasets/VFDB')

# 外部resfinder文件数据路径 
EXTERNAL_RESFINDER_PATH = os.path.join(BASE_DIR, 'datasets/resfinder')


'''
项目初始化启动时,为了加强API访问的效率(避免多次打开/关闭文件),将读取SRP项目表、SRP去重项目表、规范化SRP深度和经纬度项目表进行字典对象化
'''
from app.utils.read_csv_as_objects import read_csv_as_objects
from app.utils.read_detailed_sra_info import read_detailed_sra_info
# 读取SRP项目表
SRP_INFO = read_csv_as_objects(os.path.join(DATABASE_PATH, SRP_INFO_FILE))
# 读取SRP去重项目表
# SRP_DEDUPLICATED_INFO = read_csv_as_objects(DATABASE_PATH + '/' + SRP_DEDUPLICATED_INFO_FILE)
# 读取规范化SRP深度和经纬度项目表
SRP_INFO_WITH_DEPTH_AND_LONGITUDE_AND_LATITUDE = read_detailed_sra_info()



# celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

